import { Toaster } from '@/components/ui/toaster';
import { ClientProviders } from '@/hooks/useProvider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../../styles/global.css';
import { DashboardHeader } from './header';
import { ReactQueryProvider } from './react-query-provider';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientProviders>
      <html lang="en">
        <body className={inter.className}>
          <ReactQueryProvider>
            <div vaul-drawer-wrapper="" className=" flex-col flex ">
              <DashboardHeader />
              <div className="flex-1 space-y-4 pt-6 max-w-[1680px] w-full mx-auto mt-12">
                {children}
              </div>
            </div>
          </ReactQueryProvider>
          <Toaster />
        </body>
      </html>
    </ClientProviders>
  );
}
